#! /bin/env bash

# set -e

# Variables
storePath=~/Documents/.scripts/configFiles

# Home directory
cd ~
cp .bashrc $storePath
# cp .vimrc $storePath

# neovim testing config from neovim kickstart https://github.com/nvim-lua/kickstart.nvim
cd ~/.config/nvim
cp init.lua $storePath/nvimConfig 

# swaywm
cd ~/.config/sway
cp config $storePath/config.sway

# waybar
cd ~/.config/waybar
cp config $storePath/config.waybar
cp style.css $storePath/syle.css.waybar

# alacritty
cd ~/.config/alacritty
cp alacritty.yml $storePath/

#if $1
#then
# cd ~/Documents/.scripts/ConfigFiles/
# git add $1 $2 $3 $4 $5
# git commit
# git push
#fi
